// Type-only import: erased at compile time, so it adds nothing to the
// bundle. The actual jsPDF runtime is loaded on demand inside
// generatePdfReport() below, since it's a sizeable dependency that only
// the small fraction of users who click "Download PDF Report" need.
import type { jsPDF } from "jspdf";
import type { LatestResumeReport } from "@/types/report.types";
import type { AtsCategoryBreakdown } from "@/types/ats.types";
import type { RewriteLineItem } from "@/types/rewrite.types";
import type { InterviewQuestion, InterviewQuestionSet } from "@/types/interview.types";

/**
 * PDF Report Generator (Step 11).
 *
 * Renders the current in-session `LatestResumeReport` (Step 10's shape)
 * as a downloadable PDF using jsPDF's native text/vector API — no
 * html2canvas, no DOM screenshotting. This keeps the output crisp,
 * text-selectable, and independent of whatever is currently on screen,
 * and avoids embedding any custom web fonts or secrets in the bundle.
 *
 * Every section reads defensively: any field, sub-object, or array may
 * be missing depending on how far the user's session got, and each
 * accessor below falls back to "Not available" rather than throwing.
 * This file has no side effects other than `doc.save()`, which
 * triggers a client-side download — nothing is ever sent to a server.
 */

const NOT_AVAILABLE = "Not available";

export class PdfGenerationError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "PdfGenerationError";
  }
}

const safeText = (value: string | null | undefined): string =>
  value && value.trim().length > 0 ? value.trim() : NOT_AVAILABLE;

const safeNumber = (value: number | null | undefined, suffix = ""): string =>
  typeof value === "number" && Number.isFinite(value) ? `${value}${suffix}` : NOT_AVAILABLE;

const safeList = (values: string[] | null | undefined): string[] =>
  values && values.length > 0 ? values : [NOT_AVAILABLE];

const formatGeneratedDate = (): string =>
  new Date().toLocaleDateString(undefined, {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

// ---------------------------------------------------------------------------
// Layout primitives
// ---------------------------------------------------------------------------

const PAGE_MARGIN = 48;
const LINE_HEIGHT = 14;
const FOOTER_TEXT = "Generated by AI Resume Analyzer";

/**
 * Thin cursor wrapper around jsPDF that tracks vertical position, wraps
 * text to the content width, and paginates automatically. Keeping this
 * local to the module (rather than a shared layout library) is
 * intentional — this is the only place in the app that produces PDFs.
 */
class ReportCursor {
  private readonly doc: jsPDF;
  private readonly pageWidth: number;
  private readonly pageHeight: number;
  private readonly contentWidth: number;
  private y: number;

  constructor(doc: jsPDF) {
    this.doc = doc;
    this.pageWidth = doc.internal.pageSize.getWidth();
    this.pageHeight = doc.internal.pageSize.getHeight();
    this.contentWidth = this.pageWidth - PAGE_MARGIN * 2;
    this.y = PAGE_MARGIN;
  }

  private ensureSpace(needed: number) {
    if (this.y + needed > this.pageHeight - PAGE_MARGIN) {
      this.doc.addPage();
      this.y = PAGE_MARGIN;
    }
  }

  spacer(height = 8) {
    this.y += height;
  }

  divider() {
    this.ensureSpace(12);
    this.doc.setDrawColor(217, 218, 212); // --color-line
    this.doc.line(PAGE_MARGIN, this.y, this.pageWidth - PAGE_MARGIN, this.y);
    this.y += 16;
  }

  coverTitle(text: string) {
    this.ensureSpace(40);
    this.doc.setFont("times", "bold");
    this.doc.setFontSize(22);
    this.doc.setTextColor(20, 23, 31); // --color-ink
    this.doc.text(text, this.pageWidth / 2, this.y + 10, { align: "center" });
    this.y += 34;
  }

  sectionHeader(text: string) {
    this.ensureSpace(28);
    this.doc.setFont("courier", "bold");
    this.doc.setFontSize(11);
    this.doc.setTextColor(45, 106, 99); // --color-signal
    this.doc.text(text.toUpperCase(), PAGE_MARGIN, this.y);
    this.y += 8;
    this.doc.setDrawColor(45, 106, 99);
    this.doc.line(PAGE_MARGIN, this.y, PAGE_MARGIN + 36, this.y);
    this.y += 16;
  }

  subheading(text: string) {
    this.ensureSpace(16);
    this.doc.setFont("helvetica", "bold");
    this.doc.setFontSize(10.5);
    this.doc.setTextColor(20, 23, 31);
    this.doc.text(text, PAGE_MARGIN, this.y);
    this.y += LINE_HEIGHT;
  }

  keyValue(label: string, value: string) {
    this.ensureSpace(LINE_HEIGHT);
    this.doc.setFont("helvetica", "normal");
    this.doc.setFontSize(10);
    this.doc.setTextColor(74, 78, 89); // --color-ink-soft
    this.doc.text(`${label}:`, PAGE_MARGIN, this.y);
    this.doc.setTextColor(20, 23, 31);
    this.doc.setFont("helvetica", "bold");
    this.doc.text(value, PAGE_MARGIN + 130, this.y);
    this.y += LINE_HEIGHT;
  }

  paragraph(text: string) {
    this.doc.setFont("helvetica", "normal");
    this.doc.setFontSize(10);
    this.doc.setTextColor(20, 23, 31);
    const lines: string[] = this.doc.splitTextToSize(text, this.contentWidth);
    for (const line of lines) {
      this.ensureSpace(LINE_HEIGHT);
      this.doc.text(line, PAGE_MARGIN, this.y);
      this.y += LINE_HEIGHT;
    }
  }

  bulletList(items: string[]) {
    this.doc.setFont("helvetica", "normal");
    this.doc.setFontSize(10);
    this.doc.setTextColor(20, 23, 31);
    for (const item of items) {
      const lines: string[] = this.doc.splitTextToSize(item, this.contentWidth - 14);
      lines.forEach((line, index) => {
        this.ensureSpace(LINE_HEIGHT);
        const prefix = index === 0 ? "\u2022 " : "  ";
        this.doc.text(`${prefix}${line}`, PAGE_MARGIN, this.y);
        this.y += LINE_HEIGHT;
      });
    }
  }

  originalRewrittenPair(label: string, original: string, rewritten: string) {
    this.subheading(label);
    this.doc.setFont("helvetica", "italic");
    this.doc.setFontSize(9.5);
    this.doc.setTextColor(74, 78, 89);
    this.ensureSpace(LINE_HEIGHT);
    this.doc.text("Original:", PAGE_MARGIN, this.y);
    this.y += LINE_HEIGHT;
    this.paragraph(safeText(original));
    this.spacer(4);

    this.doc.setFont("helvetica", "italic");
    this.doc.setFontSize(9.5);
    this.doc.setTextColor(45, 106, 99);
    this.ensureSpace(LINE_HEIGHT);
    this.doc.text("Improved:", PAGE_MARGIN, this.y);
    this.y += LINE_HEIGHT;
    this.paragraph(safeText(rewritten));
    this.spacer(10);
  }

  addFootersToAllPages() {
    const pageCount = this.doc.getNumberOfPages();
    for (let page = 1; page <= pageCount; page += 1) {
      this.doc.setPage(page);
      this.doc.setFont("courier", "normal");
      this.doc.setFontSize(8);
      this.doc.setTextColor(74, 78, 89);
      this.doc.text(FOOTER_TEXT, this.pageWidth / 2, this.pageHeight - 24, { align: "center" });
      this.doc.text(
        `Page ${page} of ${pageCount}`,
        this.pageWidth - PAGE_MARGIN,
        this.pageHeight - 24,
        { align: "right" },
      );
    }
  }
}

// ---------------------------------------------------------------------------
// Section builders
// ---------------------------------------------------------------------------

const renderAtsCategory = (cursor: ReportCursor, label: string, category: AtsCategoryBreakdown | undefined) => {
  if (!category) {
    cursor.keyValue(label, NOT_AVAILABLE);
    return;
  }
  cursor.keyValue(label, `${safeNumber(category.score)} / ${safeNumber(category.maxScore)}`);
  if (category.reason) {
    cursor.paragraph(category.reason);
  }
  if (category.lostPoints && category.lostPoints.length > 0) {
    cursor.bulletList(category.lostPoints);
  }
  cursor.spacer(6);
};

const rewriteLabelSuffix = (status: RewriteLineItem["status"]): string =>
  status === "already-strong" ? " (Already Strong)" : "";

const renderRewriteLineItems = (cursor: ReportCursor, label: string, items: RewriteLineItem[] | undefined) => {
  if (!items || items.length === 0) {
    cursor.subheading(label);
    cursor.paragraph(NOT_AVAILABLE);
    cursor.spacer(10);
    return;
  }
  items.forEach((item, index) => {
    cursor.originalRewrittenPair(
      `${label} ${index + 1}${rewriteLabelSuffix(item.status)}`,
      item.original,
      item.rewritten,
    );
  });
};

const renderInterviewCategory = (cursor: ReportCursor, label: string, questions: InterviewQuestion[] | undefined) => {
  cursor.subheading(label);
  if (!questions || questions.length === 0) {
    cursor.paragraph(NOT_AVAILABLE);
    cursor.spacer(6);
    return;
  }
  questions.forEach((q, index) => {
    cursor.paragraph(`${index + 1}. (${safeText(q.difficulty)}) ${safeText(q.question)}`);
    cursor.paragraph(`Why it's asked: ${safeText(q.whyAsked)}`);
    cursor.spacer(4);
  });
  cursor.spacer(6);
};

// ---------------------------------------------------------------------------
// Entry point
// ---------------------------------------------------------------------------

/**
 * Generates and downloads a PDF report from the given resume report.
 * Async because jsPDF itself is loaded on demand here (see the
 * type-only import note above) — awaiting this function is required.
 * Throws/rejects with `PdfGenerationError` if there is no report yet,
 * or if jsPDF itself fails partway through — callers (e.g.
 * DownloadReportButton) are expected to catch this and show an inline
 * error message.
 */
export const generatePdfReport = async (report: LatestResumeReport | null): Promise<void> => {
  if (!report || !report.file) {
    throw new PdfGenerationError("No resume report is available to export yet.");
  }

  try {
    const { jsPDF: JsPdfCtor } = await import("jspdf");
    const doc = new JsPdfCtor({ unit: "pt", format: "a4" });
    const cursor = new ReportCursor(doc);

    // 1. Cover header
    cursor.coverTitle("AI Resume Analyzer Report");
    cursor.spacer(4);
    cursor.divider();

    // 2. Candidate info
    cursor.sectionHeader("Candidate Info");
    cursor.keyValue("Name", safeText(report.parsedResume?.basicInfo.name));
    cursor.keyValue("Email", safeText(report.parsedResume?.basicInfo.email));
    cursor.keyValue("Phone", safeText(report.parsedResume?.basicInfo.phone));
    cursor.keyValue("File name", safeText(report.file?.originalName));
    cursor.keyValue("Generated on", formatGeneratedDate());
    cursor.spacer(10);

    // 3. Resume metrics
    cursor.sectionHeader("Resume Metrics");
    cursor.keyValue("ATS Score", safeNumber(report.ats?.overallScore, " / 100"));
    cursor.keyValue("ATS Label", safeText(report.ats?.label));
    cursor.keyValue("Confidence", safeNumber(report.ats?.confidence, "%"));
    cursor.keyValue("JD Match Score", safeNumber(report.jdMatch?.matchScore, " / 100"));
    cursor.keyValue("JD Match Label", safeText(report.jdMatch?.label));
    cursor.spacer(10);

    // 4. AI Analysis
    cursor.sectionHeader("AI Analysis");
    cursor.subheading("Overall Summary");
    cursor.paragraph(safeText(report.analysis?.overallSummary));
    cursor.spacer(8);
    cursor.subheading("Strengths");
    cursor.bulletList(safeList(report.analysis?.strengths));
    cursor.spacer(8);
    cursor.subheading("Weaknesses");
    cursor.bulletList(safeList(report.analysis?.weaknesses));
    cursor.spacer(8);
    cursor.subheading("Recommendations");
    cursor.bulletList(safeList(report.analysis?.recommendations));
    cursor.spacer(10);

    // 5. ATS Breakdown
    cursor.sectionHeader("ATS Breakdown");
    const breakdown = report.ats?.breakdown;
    renderAtsCategory(cursor, "Resume Completeness", breakdown?.resumeCompleteness);
    renderAtsCategory(cursor, "Skills", breakdown?.skills);
    renderAtsCategory(cursor, "Experience", breakdown?.experience);
    renderAtsCategory(cursor, "Education", breakdown?.education);
    renderAtsCategory(cursor, "Projects", breakdown?.projects);
    renderAtsCategory(cursor, "AI Bonus", breakdown?.aiBonus);

    // 6. JD Match
    cursor.sectionHeader("Job Description Match");
    cursor.subheading("Matched Skills");
    cursor.bulletList(safeList(report.jdMatch?.matchedSkills));
    cursor.spacer(8);
    cursor.subheading("Missing Skills");
    cursor.bulletList(safeList(report.jdMatch?.missingSkills));
    cursor.spacer(8);
    cursor.subheading("Keyword Overlap");
    cursor.bulletList(safeList(report.jdMatch?.keywordOverlap));
    cursor.spacer(8);
    cursor.subheading("Recommendations");
    cursor.bulletList(safeList(report.jdMatch?.recommendations));
    cursor.spacer(10);

    // 7. Resume Rewrite Preview
    cursor.sectionHeader("Resume Rewrite Preview");
    const rewriteSections = report.rewrite?.sections;
    cursor.originalRewrittenPair(
      `Summary${rewriteLabelSuffix(rewriteSections?.summary.status)}`,
      rewriteSections?.summary.original ?? "",
      rewriteSections?.summary.rewritten ?? "",
    );
    renderRewriteLineItems(cursor, "Experience", rewriteSections?.experience);
    renderRewriteLineItems(cursor, "Project", rewriteSections?.projects);

    // 8. Interview Questions
    cursor.sectionHeader("Interview Questions");
    const interview: InterviewQuestionSet | null = report.interview ?? null;
    renderInterviewCategory(cursor, "Technical", interview?.technical);
    renderInterviewCategory(cursor, "Project", interview?.project);
    renderInterviewCategory(cursor, "Behavioral", interview?.behavioral);
    renderInterviewCategory(cursor, "HR", interview?.hr);

    // 9. Footer (added last, applied retroactively to every page)
    cursor.addFootersToAllPages();

    const baseName = (report.file?.originalName || "resume").replace(/\.[^/.]+$/, "");
    doc.save(`${baseName}-analysis-report.pdf`);
  } catch (error) {
    throw new PdfGenerationError(
      error instanceof Error
        ? `Failed to generate the PDF report: ${error.message}`
        : "Failed to generate the PDF report.",
    );
  }
};
